access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}



spring:
  profiles:
    active : dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/ElectricStation?retryWrites=true&w=majority
      database: ElectricStation

logging:
  level:
    org.springframework.security: DEBUG
